---
- include_tasks: mysql_root_pw.yml

- name: debian | installing pre-reqs
  apt:
    name: "{{ mysql_pre_req_packages }}"
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | installing mysql
  apt:
    name: "{{ mysql_package }}"
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | configuring mysql
  template:
    src: etc/mysql/my.cnf.j2
    dest: /etc/mysql/my.cnf
    owner: root
    group: root
    mode: 0644
  register: mysql_reconfigured_14_04
  become: true
  notify: restart mysql
  when: >
    (ansible_distribution == "Ubuntu" and
    ansible_distribution_version is version('14.04', '<=')) or
    ansible_distribution == "Debian"

- name: debian | configuring mysql
  template:
    src: etc/mysql/mysql.conf.d/mysqld.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    owner: root
    group: root
    mode: 0644
  register: mysql_reconfigured_16_04
  become: true
  notify: restart mysql
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('16.04', '>=')

- name: debian | configuring mysql
  template:
    src: etc/mysql/mysql.conf.d/mysqld.cnf.j2
    dest: /etc/mysql/conf.d/mysqld.cnf
    owner: root
    group: root
    mode: 0644
  register: mysql_reconfigured_debian
  become: true
  notify: restart mysql
  when: ansible_distribution == "Debian"

- name: debian | configuring client configuration
  template:
    src: etc/mysql/conf.d/client.cnf.j2
    dest: /etc/mysql/conf.d/client.cnf
    owner: root
    group: root
    mode: 0644
  notify: reload mysql
  become: true
  when:
    - ansible_distribution_version is version('14.04', '<=')
