---
- name: redhat | installing pre-reqs
  yum:
    name:
      - MySQL-python
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution != "Fedora"

- name: redhat | installing mysql CentOS 6
  yum:
    name:
      - mysql-server
      - mysql
    state: present
  become: true
  register: result
  until: result is successful
  when:
    - ansible_distribution != "Fedora"
    - ansible_distribution_version is version('7', '<')

- name: redhat | Installing Pre-Reqs On Fedora
  dnf:
    name:
      - libselinux-python
      - mysql-devel
      - python-devel
      - python-dnf
      - python-mysql
    state: present
  become: true
  register: result
  until: result is successful
  when:
    - ansible_distribution == "Fedora"
    - ansible_distribution_version is version('30', '<')

- name: redhat | Installing Pre-Reqs On Fedora
  dnf:
    name:
      - mysql-devel
      - python3-devel
      - python3-dnf
      - python3-libselinux
      - python3-mysql
    state: present
  become: true
  register: result
  until: result is successful
  when:
    - ansible_distribution == "Fedora"
    - ansible_distribution_version is version('30', '>=')

- name: redhat | Installing MySQL Fedora
  dnf:
    name:
      - mysql-server
      - mysql
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution == "Fedora"

- name: redhat | Ensuring mysqld Is Enabled and Starts On Boot
  service:
    name: mysqld
    state: started
    enabled: true
  become: true
  when: >
    (ansible_distribution == "CentOS" and
    ansible_distribution_version is version('7', '<')) or
    (ansible_distribution == "Fedora" and
    (ansible_distribution_version is version('24', '==') or
    ansible_distribution_version is version('25', '==')))

- name: redhat | installing mariadb mysql CentOS 7
  yum:
    name: ["mariadb-server", "mariadb"]
    state: present
  become: true
  register: result
  until: result is successful
  when:
    - ansible_distribution != "Fedora"
    - ansible_distribution_version is version('7', '>=')

- name: redhat | configuring mysql
  template:
    src: etc/my.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: root
    mode: 0644
  register: mariadb_reconfigured_redhat
  become: true
  notify: restart mariadb
  when:
    - ansible_distribution != "Fedora"
    - ansible_distribution_version is version('7', '>=')

- name: redhat | Ensuring mariadb Service Is Enabled and Starts On Boot
  service:
    name: mariadb
    state: started
    enabled: true
  become: true
  when: >
    (ansible_distribution == "CentOS" and
    ansible_distribution_version is version('7', '>=')) or
    (ansible_distribution == "Fedora" and
    (ansible_distribution_version is version('23', '<=') or
    ansible_distribution_version is version('26', '>=')))
