---
- name: set_facts | Setting Debian Facts
  set_fact:
    mysql_package: mysql-server
    mysql_pre_req_packages:
      - automysqlbackup
      - software-properties-common
      - python-mysqldb
      - rsync
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_version is version('9', '<')

- name: set_facts | Setting Debian Facts
  set_fact:
    mysql_package: mariadb-server
    mysql_pre_req_packages:
      - automysqlbackup
      - software-properties-common
      - python-mysqldb
      - rsync
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_version is version('9', '>=')

- name: set_facts | Setting Ubuntu Facts
  set_fact:
    mysql_package: mysql-server
    mysql_pre_req_packages:
      - automysqlbackup
      - software-properties-common
      - python-mysqldb
      - rsync
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('18.04', '<')

- name: set_facts | Setting Ubuntu Facts
  set_fact:
    mysql_package: mysql-server
    mysql_pre_req_packages:
      - automysqlbackup
      - software-properties-common
      - python3-mysqldb
      - rsync
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('18.04', '>=')
